// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Metadata information about an archive.
 */
export type ArchiveInfo = { 
/**
 * Archive format (e.g., "ZIP", "TAR", "7Z")
 */
format: string, 
/**
 * Number of entries in the archive
 */
entries: number, 
/**
 * Compressed size in bytes (if available)
 */
compressed_bytes?: number, 
/**
 * Estimated uncompressed size in bytes (if available)
 */
uncompressed_estimate?: number, 
/**
 * Whether the archive is password-protected
 */
encrypted: boolean, };
