// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Individual entry within an archive.
 */
export type ArchiveEntry = { 
/**
 * Path of the entry within the archive
 */
path: string, 
/**
 * Whether this entry is a directory
 */
is_directory: boolean, 
/**
 * Uncompressed size in bytes
 */
size: number, 
/**
 * Compressed size in bytes (if available)
 */
compressed_size?: number, };
