// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtractStats } from "./ExtractStats";
import type { JobStatus } from "./JobStatus";

/**
 * Completion event payload
 */
export type CompletionEvent = {
	jobId: string;
	archivePath: string;
	status: JobStatus;
	stats?: ExtractStats;
	error?: string;
};
