// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Statistics about a completed extraction operation.
 */
export type ExtractStats = {
	/**
	 * Number of files successfully extracted
	 */
	files_extracted: number;
	/**
	 * Total bytes written to disk
	 */
	bytes_written: number;
	/**
	 * Duration of the extraction operation (in seconds)
	 */
	duration: number;
	/**
	 * Whether the extraction was cancelled
	 */
	cancelled: boolean;
};
