// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * File system entry metadata
 */
export type FileSystemEntry = { name: string, path: string, isDirectory: boolean, isArchive: boolean, size?: number, modifiedAt?: number, };
