// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Password required event payload
 */
export type PasswordRequiredEvent = { jobId: string, archivePath: string, };
