// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Progress event payload
 */
export type ProgressEvent = {
	jobId: string;
	archivePath: string;
	currentFile: string;
	bytesWritten: number;
	totalBytes?: number;
};
