// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Settings structure for persistence
 */
export type SettingsData = {
	overwriteMode: string;
	sizeLimitGb: number;
	stripComponents: number;
	allowSymlinks: boolean;
	allowHardlinks: boolean;
};
