// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * DTO for extraction options from frontend
 */
export type ExtractOptionsDTO = { overwrite: string, sizeLimitBytes?: bigint, stripComponents: number, allowSymlinks: boolean, allowHardlinks: boolean, password?: string, };
